/* ### LISTAS ### */
//LISTA DE SEXOS
const listaSexo = //deixa pro final!!!
[
    'homem',
    'mulher'
]
const listaClasse = 
[
    'GUERREIRO',
    'GUERREIRO',
    'GUERREIRO',
    'GUERREIRO',
    'GUERREIRO',
    'GUERREIRO',
    'LADRÃO',
    'LADRÃO',
    'LADRÃO',
    'CLÉRIGO',
    'CLÉRIGO',
    'FEITICEIRO'
]

const listaVirtudes = [
    'altruísmo',
    'amabilidade', 
    'ambição',
    'amigável',
    'benevolência',
    'bondade',
    'caridade',
    'castidade',
    'cautela',
    'clemente',
    'compaixão',
    'confiança',
    'confiável',
    'consideração',
    'cooperação',
    'coragem',
    'cortesia',
    'criatividade',
    'curiosidade',
    'desafiador',
    'destemor',
    'determinado',
    'disciplinado',
    'engenhosidade',
    'engraçado',
    'entusiasmado',
    'esperançoso',
    'firmeza',
    'focado',
    'frugal',
    'generoso',
    'gregário',
    'honestidade',
    'honra',
    'humildade',
    'idealista',
    'imparcialidade',
    'justo',
    'lealdade',
    'metódico',
    'misericórdia',
    'ousadia',
    'paciência',
    'persistência',
    'piedade',
    'prestativo',
    'respeito',
    'responsabilidade',
    'tato',
    'tolerância'
]

const listaVícios = [
    'agressivo',
    'alcoólatra', 
    'ambicioso',
    'antagônico',
    'arrogante',
    'cobiçoso',
    'colérico',
    'covarde',
    'cruel',
    'decadente',
    'desleal',
    'egoísta',
    'esnobe',
    'falso',
    'fanático',
    'fanfarrão',
    'glutão',
    'hedonista',
    'impaciente',
    'implacável',
    'imprudente',
    'incrédulo',
    'inflexível',
    'interesseiro',
    'invejoso',
    'irritável',
    'lamenta-se de tudo',
    'lascivo',
    'louco',
    'malicioso',
    'manipulador',
    'mentiroso',
    'mesquinho',
    'negligente',
    'obsessivo',
    'perdulário',
    'petulante',
    'preconceituoso',
    'preguiçoso',
    'ressentido',
    'rude',
    'sanguinário',
    'sem compaixão',
    'sensual',
    'teimoso',
    'temperamental',
    'trapaceiro',
    'vaidoso',
    'viciado em apostas',
    'vingativo'
]

const listaAparGuerreiro = [
    'pés grandes',
    'boca grande',
    'bigode grande',
    'nariz notável',
    'tranças no cabelo',
    'nariz quebrado',
    'corpo definido',
    'olhos límpidos',
    'fenda no queixo',
    'dentes tortos',
    'cabelo encaracolado',
    'pele escura',
    'voz profunda',
    'sujo',
    'brincos',
    'lacuna nos dentes',
    'cavanhaque',
    'bandana',
    'bochechudo',
    'cabeludo',
    'queixo comprido',
    'orelhas grandes',
    'mãos grandes ',
    'cabeça grande',
    'pernas compridas',
    'cabelo emaranhado',
    'orelha faltando',
    'caolho',
    'dedo faltando ',
    'dentes faltando',
    'botas notáveis',
    'elmo notável',
    'postura perfeita',
    'pele marcada',
    'pele com acne',
    'voz rouca',
    'bochechas rosadas',
    'sandálias',
    'cheio de cicatrizes',
    'tatuagens',
    'cabeça raspada',
    'fedido',
    'sempre sorridente',
    'franze o cenho',
    'olhar metálico',
    'barba por fazer',
    'tatuagens',
    'nunca sorri',
    'impecavelmente limpo',
    'jovial'
]

const listaAparLadrão = [
    'barba por fazer',
    'bem vestido',
    'bigode fino',
    'boca pequena',
    'cabelo emaranhado',
    'cabelo frontal em “v”',
    'cabeludo',
    'calçado notável',
    'caolho',
    'cavanhaque',
    'chapéu/gorro notável',
    'cheio de cicatrizes',
    'dedo faltando',
    'dedos longos',
    'dentes faltando',
    'dentes tortos',
    'desfigurado',
    'despenteado',
    'encapuzado',
    'esquelético ',
    'fedido',
    'franze o cenho',
    'cara lisa',
    'lacuna nos dentes',
    'luvas notáveis',
    'manco',
    'mãos pequenas',
    'não toma banho',
    'nariz notável',
    'nariz quebrado',
    'nunca sorri',
    'olhar desonesto',
    'olhos avermelhados',
    'olhos estreitos',
    'olhos límpidos',
    'pálido',
    'pele escura',
    'pele com acne',
    'postura horrível',
    'postura perfeita',
    'queixo pontudo',
    'roupas que não combinam',
    'sobremordida',
    'suíças',
    'tatuagens',
    'voz profunda',
    'voz rouca',
    'voz sussurrante'
]

const listaAparClérigo = [
    'bandana',
    'barba longa',
    'barba por fazer',
    'bochechas rozadas',
    'brincos',
    'cabeça raspada',
    'cabelo em tonsura',
    'cabelo encaracolado',
    'cabeludo',
    'carrega uma mitra',
    'caspa',
    'cavanhaque',
    'cheio de cicatrizes',
    'dentes faltando',
    'dentes tortos',
    'elmo notável',
    'encapuzado',
    'encorpado',
    'esquelético',
    'fedido',
    'fenda no queixo',
    'grisalho',
    'cara lisa',
    'impecavelmente limpo',
    'mãos grandes',
    'marcas estranhas',
    'monocelha',
    'não toma banho',
    'nariz notável',
    'olhar penetrante',
    'olhos ardentes',
    'olhos brilhantes',
    'olhos límpidos',
    'ombros largos',
    'pálido',
    'pele escura',
    'pele com acne',
    'perfumado',
    'pés grandes',
    'postura perfeita',
    'queixo quadrado',
    'sempre sorridente',
    'sujo',
    'tatuagens',
    'testa larga',
    'tiara/testeira',
    'verrugas',
    'vestimentas notáveis',
    'voz retumbante'
]

const listaAparFeiticeiro = [
    'abatido',
    'bandana',
    'barba longa',
    'bochechudo',
    'cabelo encaracolado',
    'cabelo frontal em “v”',
    'cabelo longo',
    'cabelos brancos',
    'careca',
    'careca',
    'cavanhaque',
    'chapéu pontudo',
    'cheio de cicatrizes',
    'cicatrizes causadas por ácido',
    'cicatrizes de queimadura',
    'dentes enegrecidos',
    'dentes faltando',
    'dentes tortos',
    'desfigurado',
    'encapuzado',
    'esquelético',
    'falhas no cabelo',
    'fedido',
    'grisalho',
    'heterocromia',
    'idoso',
    'língua bifurcada',
    'manco',
    'manto notável',
    'mãos esqueléticas',
    'mãos retorcidas',
    'marcas estranhas',
    'monocelha',
    'não toma banho',
    'nariz notável',
    'olhos brilhantes',
    'olhos fundos',
    'pele com acne',
    'pele oleosa',
    'pele pálida',
    'postura horrível',
    'sobrancelha raspada',
    'suíças',
    'tatuagens',
    'testa larga',
    'unhas longas',
    'verrugas',
    'voz retumbante',
    'voz rouca'
]
//------------------------------------------
//NOMES
const listaHumano = [
    'Athelan',
    'Aldred',
    'Alger',
    'Archard',
    'Astyrian',
    'Bowden',
    'Brogan',
    'Caden',
    'Cerdic',
    'Devan',
    'Druce',
    'Dugal',
    'Edlyn',
    'Ebis',
    'Esward',
    'Firman',
    'Framar',
    'Fugol',
    'Garret',
    'Gidwin',
    'Gord',
    'Govannon',
    'Greme',
    'Grindan',
    'Halwen',
    'Holt',
    'Iden',
    'Irbend',
    'Kendrik',
    'Leor',
    'Lufian',
    'Nyle',
    'Odel',
    'Ord',
    'Orleg',
    'Radan',
    'Reged',
    'Rowe',
    'Scrydan',
    'Seaver',
    'Shepard',
    'Snell',
    'Stedman',
    'Swift',
    'Teon',
    'Tobrec',
    'Tredan',
    'Ware',
    'Warian',
    'Wulf',
    'Falkor'
]
const listaHumana = [
    'Acca',
    'Alodia',
    'Andessa',
    'Anlis',
    'Ara',
    'Acca',
    'Alodia',
    'Andessa',
    'Anlis',
    'Ara',
    'Ardith',
    'Berroc',
    'Bernia',
    'Bodica',
    'Brigantia',
    'Brimlid',
    'Caro',
    'Cwen',
    'Darel',
    'Dawn',
    'Diera',
    'Diana',
    'Eda',
    'Elene',
    'Elga',
    'Elswyth',
    'Elva',
    'Elvina',
    'Erlina',
    'Esma',
    'Faradan',
    'Freya',
    'Garmang',
    'Gloris',
    'Harmilla',
    'Hunnar',
    'Juliana',
    'Kandara',
    'laralan',
    'Lorn',
    'Maida',
    'Megdas',
    'Mercia',
    'Mora',
    'Ogethas',
    'Ossia',
    'Pallas',
    'Rathet',
    'Sibley',
    'Sunnivar',
    'Tate',
    'Udela',
    'Viradeca',
    'Wilona',
    'Zora',
]
const listaHalflingo = [
    'Adaman',
    'Adelard',
    'Adred',
    'Agilward',
    'Arnest',
    'Adaman',
    'Adelard',
    'Adred',
    'Agilward',
    'Arnest',
    'Balbas',
    'Barton',
    'Bell',
    'Banco',
    'Bowman',
    'Cal',
    'Emmet',
    'Erling',
    'Fastman',
    'Foda',
    'Freebern',
    'Frid',
    'Gerd',
    'Hadred',
    'Hagar',
    'Halbert',
    'Hamfast',
    'Hildred',
    'Huge',
    'Isen',
]//falta os 50 restantes
const listaHalflinga = [
    'Adelle',
    'Agilward',
    'Alfreda',
    'Amalinde',
    'Balba',
    'Jilly',
    'Kat',
    'Klare',
    'Lily',
    'Lobelia',
    'Lorna',
    'Lucie',
    'Magda',
    'Marga',
    'Mari',
    'Marigold',
    'Marka',
    'Marlyn',
    'Mina',
    'Noba',
    'Olga',
    'Ottillia',
    'Pansy',
    'Pervinca',
    'Poppy',
    'Rose',
    'Rowan',
    'Salina',
    'Tella',
    'Ulrica',
]//falta os 45 anteriores
const listaAnão = [
    'Bagan',
    'Banar',
    'Belir',
    'Besil',
    'Boran',
    'Darin',
    'Dirin',
    'Doibur',
    'Doigan',
    'Fagan',
    'Fignus',
    'Firin',
    'Gesil',
    'Glagan',
    'Glasil',
    'Glenus',
    'Goirin',
    'Gosil',
    'Hanar',
    'Heran',
    'Hoibur',
    'Hoili',
    'Hoinar',
    'Holir',
    'Homli'
]//falta os 50 restantes
const listaAnã = [
    'Berin',
    'Bibura',
    'Bisil',
    'Dagna',
    'Delinia',
    'Deris',
    'Dira',
    'Disia',
    'Dorinda',
    'Faran',
    'Fasina',
    'Fignis',
    'Foifur',
    'Foimli',
    'Gerda',
    'Gestis',
    'Ginus',
    'Glegna',
    'Glelia',
    'Glelis',
    'Gloigas',
    'Gloina',
    'Glonara',
    'Hegna'
]//50 restantes
const listaElfo = [
    'Amánd',
    'Amioril',
    'Analad',
    'Anin',
    'Anumir',
    'Calithrambor',
    'Calóng',
    'Calór',
    'Cebrin',
    'Cóldor',
    'Corfindil',
    'Delithran',
    'Elithranduil',
    'Elverion',
    'Eowóril',   
    'Galithrar',
    'Gelith',
    'Gladriendil',
    'Glamir',
    'Glarang',
    'Glil-Gang',
    'Glundil',
    'Gorfilas',
    'Góriand',
    'Hal',
    'Harang',
    'Isil-Galith',
    'Isilith',
    'Isónd',
    'Isorfildur',
    'Legaraldur',
    'Lómebrildur',
    'Mil-Gan',
    'Náldur',
    'Nelith',
    'Niol',
    'Porfindel',
    'Ráldur',
    'Silmandil',
    'Tand',
    'Taralad',
    'Tararion',
    'Tendil',
    'Téril',
    'Tildur',
    'Tiniomir',
    'Unálad',
    'Unebrin',
    'Unéndil',
    'Uriong'
]
const listaElfa = [
    'Amidë',
    'Anadriedia',
    'Anarania',
    'Anebriwien',
    'Anilmadith',
    'Beliniel',
    'Calararith',
    'Cebridith',
    'Celénia',
    'Celil-Gathiel',
    'Cidien',
    'Eäróndra',
    'Eärorfindra',
    'Eláthien',
    'Eláviel',
    'Eleniel',
    'Elorfindra',
    'Elváwien',
    'Eoweclya',
    'Eowodia',
    'Fórith',
    'Gilmadith',
    'Gladrieclya',
    'Glélindë',
    'Gorfinia',
    'Hadrieviel',
    'Haniel',
    'Hebriclya',
    'Legithralia',
    'Lómithrania',
    'Meclya',
    'Mélith',
    'Módien',
    'Paclya',
    'Paradien',
    'Pedith',
    'Pil-Gandra',
    'Pirith',
    'Porficlya',
    'Sithralindë',
    'Thrédith',
    'Thrilmadith',
    'Thrithien',
    'Throrfindra',
    'Tilmaclya',
    'Tilmawen',
    'Tinilmania',
    'Uradriethiel',
    'Urithrarith',
    'Urorfiviel'
]

//------------------------------------------------------------------------------------
const listaBugiganga = [
    'ábaco',
    'alaúde',
    'aljava com flechas élficas boas',
    'ampulheta',
    'amuleto da sorte',
    'anel sinete',
    'arco curto élfico bom',
    'armadura de couro boa',
    'balde de piche',
    'baú de viagem',
    'bengala de herança',
    'bestiário',
    'boneca de criança',
    'burro',
    'cachimbo de barro e fumo',
    'caixa de música',
    'caixa de velas',
    'cálice de herança',
    'rato/gato/cobra/corvo de estimação ou algo do tipo',
    'cão de caça',
    'capa com bordas de pele',
    'carta náutica',
    'cartaz de procurado',
    'cataplasmas e ervas',
    'cavalo',
    'chapéu/barrete/capuz/elmo notável',
    'chave enferrujada',
    'chave-mestra',
    'cinto/cinturão chique',
    'conjunto de curandeiro',
    'conjunto de reparos pequenos',
    'corda(15m) e gancho de escalada',
    'crânio humanóide pequeno',
    'criatura empalhada',
    'elmo desgastado',
    'engradado de grogue',
    'engragadado de vinho',
    'enxada',
    'escudo com brasão de família',
    'escudo desgastado',
    'espada de herança',
    'espada quebrada',
    'espelho de mão',
    'estandarte de herança',
    'estatueta de madeira',
    'estatueta de pedra-sabão',
    'ferramentas de jardinagem',
    'forcado',
    'frasco com um líquido estranho',
    'frasco de remédio caseiro',
    'gaiola e ave de estimação',
    'grilhões de ferro',
    'jarro contendo parte de monstro conservado',
    'jarro de argila contendo mel',
    'jarro de narcótico',
    'jogo da bugalha/pedrinha',
    'joia',
    'joia/medalhão barato',
    'lamparina de cobre e óleo',
    'livro',
    'livro de orações',
    'luvas/manoplas notáveis',
    'machadinha',
    'manto/capa notável',
    'mão da glória',
    'mapa do tesouro',
    'martelo de guerra anão bom',
    'martelo e cunha bons de fabricação anã',
    'máscara de madeira',
    'mensagem cifrada',
    'nota promissória',
    'ocarina/flauta',
    'ovo estranho',
    'pata de monstro empalhada',
    `pederneira e ${dadosFunc(1,6)} tochas`,
    'pedra brilhante',
    'pedra de amolar boa',
    'pedra preciosa quebrada',
    'peles de animais diversos',
    'pergaminho mágico(a decifrar)',
    'pote de argila com gordura animal',
    'pote de ferro fundido',
    'punhado de sementes estranhas',
    'rede de pesca',
    'saco de carne seca',
    'saco de grãos',
    `saco de moedas com ${dadosFunc(3,18)} pratas`,
    'saco de sal',
    'sacola de bandagens',
    'sacola de ouro em pó',
    'sapatos/botas/sandálias notáveis',
    'seguidor(role um NPC)',
    'serrote pequeno',
    'símbolo sagrado',
    'tambor pequeno',
    'tapa-olho',
    'trompa de caçador',
    'vaca',
    'vara de pesca e cesta',
    'vidro de perfume'
]
//Guerreiro
const listaVestimentaGue = [
    'roupas inferiores',
    'roupas comuns'
]
const listaArmaduraGue = [
    'armadura de couro',
    'armadura de couro',
    'cota de malha',
    'cota de malha',
    'placa peitoral',
    'armadura de escamas'
]
const listaOutrosGue = [
    'broquel',
    'broquel',
    'broquel',
    'escudo',
    'escudo',
    'equipamento de aventureiro'
]
//ladrão
const listaVestimentaLad = [
    'trapos',
    'roupas inferiores',
    'roupas inferiores',
    'roupas comuns',
    'roupas comuns',
    'roupas boas'
]
const listaArmaLad = [
    'adaga',
    'adaga',
    'porrete',
    'espada curta',
    'funda e saco de pedras de funda',
    'arco curto e aljava com flechas'
]
const listaOutrosLad = [
    'tochas e pederneira',
    'gazuas',
    'gazuas',
    'armadura de couro',
    'armadura de couro',
    'equipamento de aventureiro'
]
//clérigo
const listaVestimentaCler = [
    'trapos',
    'túnica com capuz',
    'barrete e batina',
    'barrete e batina',
    'barrete e batina',
    'roupas sacerdotais'
]
const listaArmaCler = [
    'bastão ou faca',
    'bastão ou faca',
    'porrete ou adaga',
    'porrete ou adaga',
    'maça ou martelo de combate',
    'mangual ou lança'
]
const listaOutrosCler = [
    'taça de arrecadação',
    'livro sagrado',
    'livro sagrado',
    'armadura de couro',
    'armadura de couro',
    'cota de malha'
]
//feiticeiro
const listaVestimentaFei = [
    'manto esfarrapado',
    'manto esfarrapado',
    'manto comum',
    'manto comum',
    'manto comum',
    'manto bom'
]
const listaCabeçaFei = [
    'capuz',
    'capuz',
    'solidéu',
    'tiara ou testeira',
    'turbante',
    'chapéu pontudo'
]
const listaArmaFei = [
    'bastão',
    'bastão',
    'bastão',
    'faca',
    'faca',
    'adaga'
]
const listaOutrosFei = [
    'antitoxina',
    'conjunto de escrita',
    'conjunto de escrita',
    'sacola de livros',
    'sacola de livros',
    `componentes mágicos ${dadosFunc(1,6)} usos`
]
/* ######################################################################## */
//AVENTURA
const listaVerbo = [
    'PROTEGER',
    'DESTRUIR',
    'CAPTURAR',
    'CONVENCER',
    'ROUBAR',
    'CONTROLAR',
    'RESGATAR',
    'ENCONTRAR',
    'DETER',
    'DESCOBRIR',
    'ESCAPAR',
    'SOBREVIVER'
]
const listaSubstantivo = [
    'HUMANÓIDE',
    'CRIATURA(ANIMAL, MONSTRO, SER MÁGICO)',
    'GRUPO(GOVERNO, SEITA, REUNIÃO, ORGANIZAÇÃO)',
    'ARTEFATO(COMUM, MÁGICO, VALIOSO, MECÂNICO)',
    'LUGAR(ÁREA, REGIÃO, ASSENTAMENTO, QUARTO)',
    'EVENTO(CELEBRAÇÃO, DESAFIO, FENÔMENO NATURAL/MÁGICO)',
]
const listaComplicacao = [
    'SEM SER VISTO',
    'A TEMPO',
    'CONFUSÃO',
    'DILEMA',
    'TRAIÇÃO',
    'DESVANTAGEM',
    'LOCAL ESPECÍFICO',
    'CAOS'
]
const listaFinalidade = [
    'AMOR',
    'DEVER',
    'PODER',
    'ÓDIO'
]
const listaDesastre = [
    'TIRANIA',
    'PESTILÊNCIA',
    'DESTRUIÇÃO',
    'USURPAÇÃO',
    'EMPOBRECIMENTO',
    'CAOS EXCESSIVO'
]
const listaTextura = [
    'SOCIEDADE',
    'NOBREZA',
    'CRIMINALIDADE',
    'DIVINO',
    'PROFANO',
    'ASSOMBRAMENTO',
    'SELVAGERIA',
    'MILITARISMO',
    'RUÍNAS',
    'ALIENÍGENA',
    'MÁGICO',
    'TECNOLÓGICO'
]
//magia
const listaForma = [
    'adaga',
    'animal',
    'arma',
    'armadilha',
    'armadura',
    'asas',
    'aspecto',
    'ataque',
    'aura',
    'báculo',
    'banquete',
    'bênção',
    'boca',
    'bolso',
    'borrão',
    'borrifo',
    'brilho',
    'cálice',
    'canção',
    'capa',
    'cérebro',
    'chamado',
    'chifre',
    'círculo',
    'cone',
    'coração',
    'coroa',
    'cubo',
    'dádiva',
    'dardo',
    'dedo',
    'demônio',
    'dente',
    'elmo',
    'elo',
    'encanto',
    'escudo',
    'esfera',
    'espada',
    'explosão',
    'face',
    'fechadura',
    'fera',
    'fissura',
    'flecha',
    'fulgor',
    'garra',
    'globo',
    'golem',
    'grito',
    'guarda',
    'guia',
    'jato',
    'juramento',
    'laço',
    'lâmina',
    'lança',
    'lembrança',
    'língua',
    'magia',
    'maldição',
    'manto',
    'mão',
    'marca',
    'martelo',
    'mente',
    'muralha',
    'olhar',
    'olho',
    'olhos',
    'onda',
    'oráculo',
    'padrão',
    'palavra',
    'passagem',
    'perdição',
    'perturbação',
    'pilar',
    'pirâmide',
    'porta',
    'portal',
    'presa',
    'proteção',
    'punho',
    'raio',
    'resplendor',
    'runa',
    'sangue',
    'selo',
    'sentinela',
    'servo',
    'seta',
    'sigilo',
    'sinal',
    'sussurro',
    'teia',
    'tempestade',
    'tentáculo',
    'unha',
    'véu',
    'voz'
]
const listaElemento = [
    'ácido',
    'aço',
    'aflição',
    'água',
    'alma',
    'almas',
    'amor',
    'ar',
    'avareza',
    'aversão',
    'barro',
    'brasas',
    'bruma',
    'calor',
    'chumbo',
    'cinzas',
    'cobiça',
    'cobre',
    'conhecimento',
    'cosmo',
    'desespero',
    'destino',
    'dimensão',
    'dor',
    'energia',
    'engano',
    'enxofre',
    'equilíbrio',
    'escuridão',
    'esperança',
    'espírito',
    'estrelas',
    'éter',
    'ferro',
    'fogo',
    'força',
    'fumaça',
    'fúria',
    'gelo',
    'glória',
    'história',
    'inveja',
    'justiça',
    'juventude',
    'lama',
    'lua',
    'luxúria',
    'luz',
    'madeira',
    'medo',
    'mentiras',
    'mercúrio',
    'metal',
    'morte',
    'natureza',
    'névoa',
    'nuvem',
    'ódio',
    'óleo',
    'osso',
    'ossos',
    'ouro',
    'pedra',
    'percepção',
    'plano',
    'planta',
    'poder',
    'podridão',
    'poeira',
    'prata',
    'raiva',
    'relâmpago',
    'repulsa',
    'ruína',
    'sabedoria',
    'saber',
    'sal',
    'sangue',
    'saúde',
    'sol',
    'solo',
    'som',
    'sombra',
    'tempestade',
    'tempo',
    'terra',
    'terror',
    'tesouro',
    'toxina',
    'vaidade',
    'vapor',
    'vazio',
    'veneno',
    'vento',
    'verdade',
    'vida',
    'vigor',
    'visão',
    'vontade',
    'voracidade'
]
const listaAdjetivo = [
    'amarelo',
    'aprisionante',
    'arcano',
    'assustador',
    'atordoado',
    'branco',
    'brilhante',
    'cacófono',
    'cegante',
    'cerúleo',
    'cintilante',
    'colérico',
    'confundível',
    'congelante',
    'definhante',
    'defletor',
    'delicado',
    'demoníaco',
    'devastador',
    'diabólico',
    'dificultoso',
    'diminuição',
    'do feiticeiro',
    'drenante',
    'empoderador',
    'enfeitiçante',
    'enfraquecedor',
    'enlouquecedor',
    'enredante',
    'envolvente',
    'errático',
    'escarlate',
    'escuro',
    'esfumaçante',
    'estonteante',
    'estranho',
    'esverdeado',
    'excruciante',
    'expansível',
    'extraplanar',
    'final',
    'flamejante',
    'flutuante',
    'gélido',
    'gotejante',
    'gritante',
    'habilidoso',
    'iluminador',
    'ilusório',
    'imparável',
    'incansável',
    'incontrolável',
    'incrível',
    'inescapável',
    'instantâneo',
    'invisível',
    'invulnerável',
    'irritante',
    'lampejante',
    'lento',
    'libertador',
    'magnífico',
    'mal',
    'maravilhoso',
    'multicolorido',
    'oculto',
    'odioso',
    'onipotente',
    'penetrante',
    'penúltimo',
    'pestilente',
    'poderoso',
    'prestativo',
    'preto',
    'prismático',
    'que-tudo-sabe',
    'que-tudo-vê',
    'radiante',
    'rejuvenescedor',
    'resplandecente',
    'restaurador',
    'revigorante',
    'rotacional',
    'sangrento',
    'sedento',
    'sensível',
    'silencioso',
    'sobrenatural',
    'sonolento',
    'superexcelente',
    'terrível',
    'transdimensional',
    'transformante',
    'trovejante',
    'velado',
    'venenoso',
    'vingativo',
    'violento',
    'violeta',
    'voraz'
]
const listaPrefixo = [
    'A',
    'Ab',
    'Aga',
    'Alha',
    'Appol'
]
const listaSufixo = [
    'ak',
    'alto',
    'ana',
    'anti',
    'aris',
    'arik'
]
